logging:
  level:
    root: INFO
  path: D:\logs
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{20} - %msg%n'
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db4free.net:3306/simba_test_sb?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: test_dev
    password: simbatest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090